version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4:6.9
    environment:
      PGADMIN_DEFAULT_PASSWORD : secret
      PGADMIN_DEFAULT_EMAIL : abdeljalil.aitetaleb@gmail.com
    ports:
      - "81:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: reporting
    ports:
      - "54320:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
  